# Generated by Django 2.2.19 on 2021-04-11 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
